### ISSUE TITLE
How do you personally use this?

### ISSUE THREAD

**Issue by TomasVotruba** [Devtronic/super-tokenizer#1]
Hey, I'm curious about all tokens, parsers and ASTs and found this package.
Just curious to ask, how do you use it in your life, your projects? What was the motivation to build this?

At first sight, looks like token parser in PHP_CodeSniffer.

**Comment by devtronic** [comment]
I had to parse different texts for a project and extract information from them. I was just too lazy to do that by hand 😅

**Comment by TomasVotruba** [comment]
Miss click, sorry :)

Like PHP code? Could share more specific examples?

**Comment by TomasVotruba** [comment]
Outdated
